#!/bin/bash
if [ -d "pathtothisdirectory" ]; then
    cd pathtothisdirectory
else
    echo "please run setup.sh"
    exit 1
fi
touch temp
rm temp
python3 menu.py pathtothisdirectory/aws.csv "${@:1}"
touch temp
chmod +x temp
. ./temp
rm temp